vich_uploader:
    db_driver: orm

    mappings:
        deputes_images:
            uri_prefix: /images/deputes
            upload_destination: '%kernel.project_dir%/public/images/deputes'
        Articles_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'    
